//! CachyBridge demo executable.
//!
//! This is deliberately a point-to-point demo: the client listens, one host
//! connects, and encrypted input events are injected on the client. The
//! current implementation also includes paired topology, clipboard, and
//! edge-handoff support.

mod clipboard;
pub mod config;
mod discovery;
pub mod handoff;
mod handoff_demo;
pub mod libei_capture;
pub mod libei_inject;
mod linux_input;
pub mod pairing;
pub mod portal_persistence;
mod portal_probe;
pub mod portal_spike;
mod protocol;
pub mod remote_spike;
pub mod seamless;
mod transport;

use std::{
    collections::BTreeSet,
    fs::{self, OpenOptions},
    io,
    io::Write,
    net::{SocketAddr, TcpListener, TcpStream},
    os::unix::fs::OpenOptionsExt,
    path::PathBuf,
    sync::mpsc::{sync_channel, Receiver, TryRecvError},
    time::{Duration, Instant},
};

use clap::{Args, Parser, Subcommand, ValueEnum};
use rand::RngCore;

use crate::{
    linux_input::{
        create_sink, list_input_devices, run_kernel_self_test, start_capture, KernelTestSource,
    },
    protocol::{Message, WireInputEvent, HEARTBEAT_INTERVAL_MS, PEER_TIMEOUT_MS},
    transport::{parse_psk, Role, SecureConnection, TransportError},
};

const DEFAULT_PORT: u16 = 45_231;
const DEFAULT_PAIRING_PORT: u16 = 45_232;
/// Authenticated topology control listener on the controlled peer. It shares
/// the already-authorized pairing port, but pairing and a running client are
/// mutually exclusive modes, so no second firewall permission is required.
const DEFAULT_CONTROL_PORT: u16 = DEFAULT_PAIRING_PORT;
const DEFAULT_CLIPBOARD_PORT: u16 = 45_234;
const INPUT_QUEUE_CAPACITY: usize = 1_024;
/// The client must service both its local return barrier and remote input.
/// One millisecond limits the event-driven EIS injection wait without busy
/// spinning a CPU core while the pointer is idle.
const CLIENT_IDLE_POLL_INTERVAL: Duration = Duration::from_millis(1);

#[derive(Debug, Parser)]
#[command(
    name = "cachybridge",
    version,
    about = "Encrypted LAN input forwarding demo"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Open the native Qt 6 v4 pairing and display-placement wizard.
    Setup {
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
        /// Override the cachybridge-setup executable (useful for development).
        #[arg(long)]
        gui: Option<PathBuf>,
    },
    /// Print a new 32-byte hexadecimal pairing PSK.
    Token {
        /// Create a new mode-0600 token file instead of printing the PSK.
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Print the default v4 pairing/topology configuration path.
    ConfigPath {
        /// Use this path instead of the normal per-user configuration path.
        #[arg(long)]
        config: Option<PathBuf>,
    },
    /// Generate a pairing PSK. Prefer --output so it is never shown in a terminal.
    PairToken {
        /// Create a new mode-0600 token file instead of printing the one-time PSK.
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Print a five-character one-time pairing code, authenticated with SPAKE2.
    PairCode,
    /// Run on the controlled client: wait for one input-owner host to connect
    /// using a one-time code, then save a fresh long-term peer key locally.
    /// The code is never saved.
    PairClient {
        /// Bind address shown to the joining machine. Use a LAN IP or 0.0.0.0.
        #[arg(long, default_value_t = default_pairing_listen_address())]
        listen: SocketAddr,
        /// One-time code, normally generated by `pair-code` in the setup UI.
        #[arg(long)]
        code: String,
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
        /// Friendly local name saved in the pairing configuration.
        #[arg(long)]
        local_name: Option<String>,
        /// Port where this controlled client's regular seamless service runs.
        #[arg(long, default_value_t = DEFAULT_PORT)]
        service_port: u16,
        /// Store persistent portal permissions for this peer.
        #[arg(long)]
        persistent_permissions: bool,
        /// Maximum time to wait for the joining machine.
        #[arg(long, default_value_t = 300)]
        timeout_seconds: u64,
    },
    /// Find controlled clients that are currently waiting for a pairing host.
    PairDiscover {
        /// How long to listen for local multicast announcements.
        #[arg(long, default_value_t = 2)]
        timeout_seconds: u64,
    },
    /// Run on the input-owner host: connect to a client displaying a one-time
    /// pairing code. This stores the received long-term key locally.
    PairHost {
        /// Client address displayed by its setup window, normally port 45232.
        #[arg(long)]
        connect: SocketAddr,
        /// The code shown by the client.
        #[arg(long)]
        code: String,
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
        /// Friendly name for this input-owner host.
        #[arg(long)]
        local_name: String,
        /// Where the client display sits relative to this host.
        #[arg(long, value_enum, default_value_t = CliPlacement::Left)]
        placement: CliPlacement,
        /// Port where this host's regular seamless service will run.
        #[arg(long, default_value_t = DEFAULT_PORT)]
        service_port: u16,
        /// Store persistent portal permissions for this peer.
        #[arg(long)]
        persistent_permissions: bool,
    },
    /// Set the friendly name for this local machine in the v4 configuration.
    ConfigSetLocalName {
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
        /// Friendly local name shown by setup/UI layers.
        #[arg(long)]
        local_name: String,
    },
    /// Add a paired peer and its display placement to the v4 configuration.
    PeerAdd {
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
        /// Friendly name shown by a GUI, such as "Left iMac".
        #[arg(long)]
        name: String,
        /// Optionally update the friendly name for this local machine.
        #[arg(long)]
        local_name: Option<String>,
        /// Endpoint used when this machine is the host/input owner.
        #[arg(long)]
        host_endpoint: SocketAddr,
        /// Endpoint used when this machine is the controlled client.
        #[arg(long)]
        client_endpoint: SocketAddr,
        /// Physical/logical position of the peer relative to this display.
        #[arg(long, value_enum)]
        placement: CliPlacement,
        /// Request persistent portal permissions for this peer.
        #[arg(long)]
        persistent_permissions: bool,
        /// Read the pairing PSK from a mode-0600 token file.
        #[arg(long)]
        psk_file: PathBuf,
        /// Optional stable 32-character hexadecimal peer ID; generated by default.
        #[arg(long)]
        id: Option<String>,
    },
    /// List configured peers without exposing pairing secrets.
    PeerList {
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
    },
    /// Persist a new horizontal peer position on both paired machines, then
    /// make the controlled side restart its portal session.
    TopologyApply {
        /// Configured 32-character peer ID.
        #[arg(long)]
        peer: String,
        /// Position of the controlled client relative to this host.
        #[arg(long, value_enum)]
        placement: CliPlacement,
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
    },
    /// Run only the encrypted shared-clipboard worker for a configured peer.
    /// Useful for diagnosing clipboard support without opening input portals.
    ClipboardSync {
        /// Configured 32-character peer ID.
        #[arg(long)]
        peer: String,
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
    },
    /// List local evdev devices that can be passed to `host --device`.
    Devices,
    /// Probe Wayland portal and libei capabilities without requesting consent.
    Doctor {
        /// Emit a machine-readable JSON report.
        #[arg(long)]
        json: bool,
    },
    /// Exercise the consent-driven controller InputCapture portal lifecycle.
    PortalSpike {
        /// Arm a barrier on the outer left edge.
        #[arg(long, required = true)]
        left: bool,
        /// Seconds to report portal signals before safe cleanup.
        #[arg(long, default_value_t = 20)]
        observe_seconds: u64,
    },
    /// Exercise the consent-driven follower RemoteDesktop portal lifecycle.
    RemoteSpike {
        /// Send a fixed +2/-2 relative-pointer proof after consent.
        #[arg(long)]
        pointer_test: bool,
    },
    /// Exercise an encrypted left-edge Enter/ACK exchange with a simulated
    /// barrier event. It never opens a portal or captures physical input.
    LeftEdgeDemo {
        /// Client IPv4/IPv6 address and port.
        #[arg(long)]
        connect: SocketAddr,
        #[command(flatten)]
        auth: PskOptions,
        /// Simulated pointer-barrier Y coordinate on this iMac.
        #[arg(long, default_value_t = 540)]
        edge_y: i32,
        #[arg(long, default_value_t = 1_920)]
        local_width: u32,
        #[arg(long, default_value_t = 1_080)]
        local_height: u32,
        /// Peer display's logical left coordinate (normally negative).
        #[arg(long, default_value_t = -1_920)]
        peer_x: i32,
        #[arg(long, default_value_t = 0)]
        peer_y: i32,
        #[arg(long, default_value_t = 1_920)]
        peer_width: u32,
        #[arg(long, default_value_t = 1_080)]
        peer_height: u32,
    },
    /// Run the follower-side RemoteDesktop session for the seamless handoff
    /// protocol. It accepts input only after an authenticated Enter/ACK.
    SeamlessClient {
        /// Address to listen on after RemoteDesktop consent is granted.
        #[arg(long, default_value_t = default_listen_address())]
        listen: SocketAddr,
        #[command(flatten)]
        auth: PskOptions,
        /// Logical width used by the host's peer-left topology. The right-edge
        /// return request is encoded at x = -1 in that topology.
        #[arg(long)]
        peer_width: u32,
        /// Vertical logical offset used by the host's peer-left topology.
        #[arg(long, default_value_t = 0)]
        peer_y: i32,
    },
    /// Start the configured controlled/client side without PSKs or portal
    /// tokens on the command line.
    SeamlessClientConfig {
        /// Configured 32-character peer ID (shown by `peer-list`).
        #[arg(long)]
        peer: String,
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
        /// Logical width for the paired left display.
        #[arg(long)]
        peer_width: u32,
        /// Vertical logical offset of the paired display.
        #[arg(long, default_value_t = 0)]
        peer_y: i32,
    },
    /// Arm the controller's left InputCapture barrier and forward to a paired
    /// client only after its encrypted Enter acknowledgement.
    SeamlessHost {
        /// Client IPv4/IPv6 address and port.
        #[arg(long)]
        connect: SocketAddr,
        #[command(flatten)]
        auth: PskOptions,
        /// Confirm that the peer is physically/logically to the left.
        #[arg(long, required = true)]
        peer_left: bool,
        /// This iMac's logical portal-zone width.
        #[arg(long)]
        local_width: u32,
        /// This iMac's logical portal-zone height.
        #[arg(long)]
        local_height: u32,
        /// Left client's logical portal-zone width.
        #[arg(long)]
        peer_width: u32,
        /// Left client's logical portal-zone height.
        #[arg(long)]
        peer_height: u32,
        /// Vertical logical offset of the client's display.
        #[arg(long, default_value_t = 0)]
        peer_y: i32,
    },
    /// Start the configured controller/host side without PSKs or portal
    /// tokens on the command line.
    SeamlessHostConfig {
        /// Configured 32-character peer ID (shown by `peer-list`).
        #[arg(long)]
        peer: String,
        /// Use this configuration file instead of the normal per-user path.
        #[arg(long)]
        config: Option<PathBuf>,
        /// This iMac's logical portal-zone width.
        #[arg(long)]
        local_width: u32,
        /// This iMac's logical portal-zone height.
        #[arg(long)]
        local_height: u32,
        /// Left client's logical portal-zone width.
        #[arg(long)]
        peer_width: u32,
        /// Left client's logical portal-zone height.
        #[arg(long)]
        peer_height: u32,
        /// Vertical logical offset of the client's display.
        #[arg(long, default_value_t = 0)]
        peer_y: i32,
    },
    /// Verify capture and injection through the real evdev/uinput kernel path.
    KernelSelfTest,
    /// Create a temporary relative-pointer source for a bounded network demo.
    KernelTestSource {
        /// Number of net-zero pointer reports to emit.
        #[arg(long, default_value_t = 5)]
        reports: u32,
        /// Time for the host to open the printed event node before emission.
        #[arg(long, default_value_t = 2_000)]
        start_delay_ms: u64,
    },
    /// Capture one or more local evdev devices and forward them to a client.
    Host {
        /// Client IPv4/IPv6 address and port, for example 192.168.1.20:45231.
        #[arg(long)]
        connect: SocketAddr,
        #[command(flatten)]
        auth: PskOptions,
        /// An evdev device to capture, e.g. /dev/input/event7. Repeat per device.
        #[arg(long = "device", required_unless_present = "demo_events")]
        devices: Vec<PathBuf>,
        /// Do not EVIOCGRAB the input devices. Suitable for initial dry runs.
        #[arg(long)]
        no_grab: bool,
        /// Send this many synthetic pointer reports, then exit cleanly.
        #[arg(long, value_name = "COUNT", conflicts_with = "devices")]
        demo_events: Option<u32>,
        /// Stop cleanly after forwarding this many evdev SYN reports.
        #[arg(long, value_name = "COUNT")]
        stop_after_reports: Option<u64>,
    },
    /// Listen for a host and inject its authenticated input events.
    Client {
        /// Address to listen on.
        #[arg(long, default_value_t = default_listen_address())]
        listen: SocketAddr,
        #[command(flatten)]
        auth: PskOptions,
        /// Validate and log events without creating a /dev/uinput device.
        #[arg(long)]
        dry_run: bool,
    },
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum CliPlacement {
    Left,
    Right,
    Above,
    Below,
}

impl From<CliPlacement> for config::RelativePlacement {
    fn from(value: CliPlacement) -> Self {
        match value {
            CliPlacement::Left => Self::Left,
            CliPlacement::Right => Self::Right,
            CliPlacement::Above => Self::Above,
            CliPlacement::Below => Self::Below,
        }
    }
}

#[derive(Debug, Args)]
struct PskOptions {
    /// 64 hexadecimal characters. Visible to local process-list readers.
    #[arg(
        long,
        conflicts_with = "psk_file",
        required_unless_present = "psk_file"
    )]
    psk: Option<String>,
    /// Read the 64-character PSK from a user-only file.
    #[arg(long, conflicts_with = "psk")]
    psk_file: Option<PathBuf>,
}

fn default_listen_address() -> SocketAddr {
    SocketAddr::from(([0, 0, 0, 0], DEFAULT_PORT))
}

fn default_pairing_listen_address() -> SocketAddr {
    SocketAddr::from(([0, 0, 0, 0], DEFAULT_PAIRING_PORT))
}

fn resolve_config_path(config_override: Option<PathBuf>) -> Result<PathBuf, config::ConfigError> {
    config_override.map_or_else(config::default_config_path, Ok)
}

fn run_setup_gui(
    config_override: Option<PathBuf>,
    gui_override: Option<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    let cachybridge = std::env::current_exe()?;
    let sibling = cachybridge
        .parent()
        .map(|directory| directory.join("cachybridge-setup"));
    let gui = gui_override
        .or_else(|| sibling.filter(|path| path.is_file()))
        .unwrap_or_else(|| PathBuf::from("cachybridge-setup"));
    let mut command = std::process::Command::new(&gui);
    command.arg("--cachybridge").arg(&cachybridge);
    if let Some(path) = config_override {
        command.arg("--config").arg(path);
    }
    let status = command.status().map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "could not launch Qt setup wizard {}: {error}; build it with `cmake -S ui -B build/ui && cmake --build build/ui`",
                gui.display()
            ),
        )
    })?;
    if status.success() {
        Ok(())
    } else {
        Err(Box::new(io::Error::other(format!(
            "Qt setup wizard exited with {status}"
        ))))
    }
}

fn main() {
    if let Err(error) = run(Cli::parse()) {
        eprintln!("cachybridge: {error}");
        std::process::exit(1);
    }
}

fn run(cli: Cli) -> Result<(), Box<dyn std::error::Error>> {
    match cli.command {
        Command::Setup { config, gui } => run_setup_gui(config, gui),
        Command::Token { output } => {
            let mut psk = [0_u8; 32];
            rand::thread_rng().fill_bytes(&mut psk);
            let encoded = hex::encode(psk);
            if let Some(path) = output {
                let mut file = OpenOptions::new()
                    .write(true)
                    .create_new(true)
                    .mode(0o600)
                    .open(&path)?;
                writeln!(file, "{encoded}")?;
                eprintln!("created {}", path.display());
            } else {
                println!("{encoded}");
            }
            Ok(())
        }
        Command::ConfigPath { config } => {
            println!("{}", resolve_config_path(config)?.display());
            Ok(())
        }
        Command::PairToken { output } => {
            let psk = config::generate_pairing_psk();
            if let Some(path) = output {
                config::write_pairing_token(&path, &psk)?;
                eprintln!("created private pairing token {}", path.display());
            } else {
                println!("{}", hex::encode(psk));
            }
            Ok(())
        }
        Command::PairCode => {
            println!("{}", pairing::generate_code());
            Ok(())
        }
        Command::PairClient {
            listen,
            code,
            config: config_override,
            local_name,
            service_port,
            persistent_permissions,
            timeout_seconds,
        } => run_pair_client(
            listen,
            &code,
            config_override,
            local_name,
            service_port,
            persistent_permissions,
            Duration::from_secs(timeout_seconds),
        ),
        Command::PairDiscover { timeout_seconds } => {
            for client in discovery::discover(Duration::from_secs(timeout_seconds))? {
                println!("{}\t{}", client.endpoint, client.name);
            }
            Ok(())
        }
        Command::PairHost {
            connect,
            code,
            config: config_override,
            local_name,
            placement,
            service_port,
            persistent_permissions,
        } => run_pair_host(
            connect,
            &code,
            config_override,
            local_name,
            placement.into(),
            service_port,
            persistent_permissions,
        ),
        Command::ConfigSetLocalName {
            config: config_override,
            local_name,
        } => {
            let path = resolve_config_path(config_override)?;
            let mut bridge_config = config::load_or_default(&path)?;
            bridge_config.local_name = local_name;
            config::save(&path, &bridge_config)?;
            println!("updated local name at {}", path.display());
            Ok(())
        }
        Command::PeerAdd {
            config: config_override,
            name,
            local_name,
            host_endpoint,
            client_endpoint,
            placement,
            persistent_permissions,
            psk_file,
            id,
        } => {
            let path = resolve_config_path(config_override)?;
            let pairing_psk = config::read_pairing_token(&psk_file)?;
            let mut peer = config::PeerConfig::new(
                id.unwrap_or_else(config::generate_peer_id),
                name,
                host_endpoint,
                client_endpoint,
                placement.into(),
                pairing_psk,
            )?;
            peer.persistent_permissions = persistent_permissions;
            let mut bridge_config = config::load_or_default(&path)?;
            if let Some(local_name) = local_name {
                bridge_config.local_name = local_name;
            }
            bridge_config.add_peer(peer.clone())?;
            config::save(&path, &bridge_config)?;
            println!(
                "added peer {} ({}) at {}",
                peer.name,
                peer.id,
                path.display()
            );
            Ok(())
        }
        Command::PeerList {
            config: config_override,
        } => {
            let path = resolve_config_path(config_override)?;
            let bridge_config = config::load_or_default(&path)?;
            for peer in bridge_config.peers {
                println!(
                    "{}\t{}\t{}\t{}\t{}",
                    peer.id,
                    peer.name,
                    peer.placement.as_str(),
                    peer.host_endpoint,
                    peer.client_endpoint
                );
            }
            Ok(())
        }
        Command::TopologyApply {
            peer,
            placement,
            config: config_override,
        } => run_topology_apply(config_override, &peer, placement.into()),
        Command::ClipboardSync {
            peer,
            config: config_override,
        } => run_clipboard_sync(config_override, &peer),
        Command::Devices => {
            let devices = list_input_devices();
            if devices.is_empty() {
                eprintln!("no readable /dev/input/event* devices found");
            }
            for device in devices {
                println!("{}\t{}", device.path.display(), device.name);
            }
            Ok(())
        }
        Command::Doctor { json } => {
            let report = portal_probe::probe();
            if json {
                println!("{}", report.to_json());
            } else {
                report.print_human();
            }
            Ok(())
        }
        Command::PortalSpike {
            left,
            observe_seconds,
        } => {
            debug_assert!(left, "clap requires --left");
            portal_spike::run_left(observe_seconds)
        }
        Command::RemoteSpike { pointer_test } => remote_spike::run(pointer_test),
        Command::LeftEdgeDemo {
            connect,
            auth,
            edge_y,
            local_width,
            local_height,
            peer_x,
            peer_y,
            peer_width,
            peer_height,
        } => run_left_edge_demo(
            connect,
            load_psk(&auth)?,
            edge_y,
            local_width,
            local_height,
            peer_x,
            peer_y,
            peer_width,
            peer_height,
        ),
        Command::SeamlessClient {
            listen,
            auth,
            peer_width,
            peer_y,
        } => run_seamless_client(listen, load_psk(&auth)?, peer_width, peer_y),
        Command::SeamlessClientConfig {
            peer,
            config: config_override,
            peer_width,
            peer_y,
        } => run_seamless_client_config(config_override, &peer, peer_width, peer_y),
        Command::SeamlessHost {
            connect,
            auth,
            peer_left,
            local_width,
            local_height,
            peer_width,
            peer_height,
            peer_y,
        } => {
            debug_assert!(peer_left, "clap requires --peer-left");
            run_seamless_host(
                connect,
                load_psk(&auth)?,
                local_width,
                local_height,
                peer_width,
                peer_height,
                peer_y,
            )
        }
        Command::SeamlessHostConfig {
            peer,
            config: config_override,
            local_width,
            local_height,
            peer_width,
            peer_height,
            peer_y,
        } => run_seamless_host_config(
            config_override,
            &peer,
            local_width,
            local_height,
            peer_width,
            peer_height,
            peer_y,
        ),
        Command::KernelSelfTest => {
            let report = run_kernel_self_test()?;
            println!("kernel input path verified");
            println!("source: {}", report.source_node.display());
            println!("receiver: {}", report.receiver_node.display());
            println!("observed events: {}", report.observed_events);
            Ok(())
        }
        Command::KernelTestSource {
            reports,
            start_delay_ms,
        } => {
            let mut source = KernelTestSource::create()?;
            println!("{}", source.event_node().display());
            io::stdout().flush()?;
            std::thread::sleep(Duration::from_millis(start_delay_ms));
            for _ in 0..reports {
                source.emit_net_zero_report()?;
                std::thread::sleep(Duration::from_millis(25));
            }
            eprintln!("emitted {reports} net-zero kernel pointer report(s)");
            Ok(())
        }
        Command::Host {
            connect,
            auth,
            devices,
            no_grab,
            demo_events,
            stop_after_reports,
        } => {
            let psk = load_psk(&auth)?;
            run_host(
                connect,
                psk,
                &devices,
                !no_grab,
                demo_events,
                stop_after_reports,
            )
        }
        Command::Client {
            listen,
            auth,
            dry_run,
        } => {
            let psk = load_psk(&auth)?;
            run_client(listen, psk, dry_run)
        }
    }
}

fn load_psk(options: &PskOptions) -> Result<[u8; 32], Box<dyn std::error::Error>> {
    let text = if let Some(path) = &options.psk_file {
        fs::read_to_string(path)?
    } else {
        options.psk.clone().expect("clap requires one PSK source")
    };
    Ok(parse_psk(text.trim())?)
}

#[allow(clippy::too_many_arguments)]
fn run_pair_client(
    listen: SocketAddr,
    code: &str,
    config_override: Option<PathBuf>,
    local_name: Option<String>,
    service_port: u16,
    persistent_permissions: bool,
    timeout: Duration,
) -> Result<(), Box<dyn std::error::Error>> {
    if service_port == 0 || timeout.is_zero() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "service port and timeout must be non-zero",
        )
        .into());
    }
    let pairing_code = pairing::normalize_code(code)?;
    let config_path = resolve_config_path(config_override)?;
    let mut bridge_config = config::load_or_default(&config_path)?;
    if let Some(name) = local_name {
        bridge_config.local_name = name;
        bridge_config.validate()?;
    }
    let listener = TcpListener::bind(listen)?;
    listener.set_nonblocking(true)?;
    let _advertiser = discovery::Advertiser::start(
        listener.local_addr()?.port(),
        bridge_config.local_name.clone(),
    )?;
    eprintln!(
        "pairing client ready on {}; waiting up to {} seconds for one code-authenticated host",
        listener.local_addr()?,
        timeout.as_secs()
    );
    let deadline = Instant::now() + timeout;
    let mut failures = 0_u8;
    loop {
        if Instant::now() >= deadline {
            return Err(
                io::Error::new(io::ErrorKind::TimedOut, "one-time pairing code expired").into(),
            );
        }
        match listener.accept() {
            Ok((stream, remote)) => {
                let local = stream.local_addr()?;
                stream.set_read_timeout(Some(Duration::from_secs(10)))?;
                stream.set_write_timeout(Some(Duration::from_secs(10)))?;
                let result = (|| -> Result<(), Box<dyn std::error::Error>> {
                    let mut connection = SecureConnection::connect_with_pairing_code(
                        stream,
                        Role::Client,
                        pairing_code.as_bytes(),
                    )?;
                    let request = pairing::decode_request(&connection.receive_payload()?)?;
                    let host_endpoint =
                        pairing::checked_endpoint(remote.ip(), request.host_service_port)?;
                    let client_endpoint = pairing::checked_endpoint(local.ip(), service_port)?;
                    let peer_id = config::generate_peer_id();
                    let long_term_psk = config::generate_pairing_psk();
                    let mut peer = config::PeerConfig::new(
                        peer_id.clone(),
                        request.host_name.clone(),
                        host_endpoint,
                        client_endpoint,
                        opposite_placement(request.placement),
                        long_term_psk,
                    )?;
                    peer.persistent_permissions =
                        persistent_permissions || request.persistent_permissions;
                    let grant = pairing::PairGrant {
                        peer_id,
                        psk: long_term_psk,
                        client_name: bridge_config.local_name.clone(),
                        client_service_port: service_port,
                        placement: request.placement,
                        persistent_permissions: peer.persistent_permissions,
                    };
                    // Send first, then commit locally. A client that cannot persist the grant
                    // may retry with a fresh code; this code is still consumed on success only.
                    connection.send_payload(&pairing::encode_grant(&grant)?)?;
                    bridge_config.add_peer(peer)?;
                    config::save(&config_path, &bridge_config)?;
                    println!(
                        "paired_peer_id={}",
                        bridge_config.peers.last().expect("peer was added").id
                    );
                    Ok(())
                })();
                match result {
                    Ok(()) => {
                        println!(
                            "paired one host; saved private configuration at {}",
                            config_path.display()
                        );
                        return Ok(());
                    }
                    Err(error) => {
                        failures = failures.saturating_add(1);
                        eprintln!("ignored unsuccessful pairing attempt from {remote}: {error}");
                        if failures >= 5 {
                            return Err(io::Error::new(
                                io::ErrorKind::PermissionDenied,
                                "too many unsuccessful pairing attempts; create a new code",
                            )
                            .into());
                        }
                    }
                }
            }
            Err(error) if error.kind() == io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(50));
            }
            Err(error) => return Err(error.into()),
        }
    }
}

fn run_pair_host(
    connect: SocketAddr,
    code: &str,
    config_override: Option<PathBuf>,
    local_name: String,
    placement: config::RelativePlacement,
    service_port: u16,
    persistent_permissions: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    if service_port == 0 {
        return Err(
            io::Error::new(io::ErrorKind::InvalidInput, "service port must be non-zero").into(),
        );
    }
    let pairing_code = pairing::normalize_code(code)?;
    let stream = TcpStream::connect_timeout(&connect, Duration::from_secs(10))?;
    let client_ip = stream.peer_addr()?.ip();
    let host_ip = stream.local_addr()?.ip();
    stream.set_read_timeout(Some(Duration::from_secs(10)))?;
    stream.set_write_timeout(Some(Duration::from_secs(10)))?;
    let mut connection =
        SecureConnection::connect_with_pairing_code(stream, Role::Host, pairing_code.as_bytes())?;
    let request = pairing::PairRequest {
        host_name: local_name.clone(),
        host_service_port: service_port,
        placement,
        persistent_permissions,
    };
    connection.send_payload(&pairing::encode_request(&request)?)?;
    let grant = pairing::decode_grant(&connection.receive_payload()?)?;
    let path = resolve_config_path(config_override)?;
    let mut bridge_config = config::load_or_default(&path)?;
    bridge_config.local_name = local_name;
    let peer = config::PeerConfig::new(
        grant.peer_id,
        grant.client_name,
        pairing::checked_endpoint(host_ip, service_port)?,
        pairing::checked_endpoint(client_ip, grant.client_service_port)?,
        grant.placement,
        grant.psk,
    )?;
    bridge_config.add_peer(peer)?;
    config::save(&path, &bridge_config)?;
    println!(
        "paired_peer_id={}",
        bridge_config.peers.last().expect("peer was added").id
    );
    println!(
        "paired client; saved private configuration at {}",
        path.display()
    );
    Ok(())
}

fn opposite_placement(placement: config::RelativePlacement) -> config::RelativePlacement {
    match placement {
        config::RelativePlacement::Left => config::RelativePlacement::Right,
        config::RelativePlacement::Right => config::RelativePlacement::Left,
        config::RelativePlacement::Above => config::RelativePlacement::Below,
        config::RelativePlacement::Below => config::RelativePlacement::Above,
    }
}

fn horizontal_placement(
    placement: config::RelativePlacement,
) -> Result<config::RelativePlacement, io::Error> {
    match placement {
        config::RelativePlacement::Left | config::RelativePlacement::Right => Ok(placement),
        config::RelativePlacement::Above | config::RelativePlacement::Below => Err(io::Error::new(
            io::ErrorKind::Unsupported,
            "top/bottom layouts are not available yet; choose left or right",
        )),
    }
}

/// Applies the client placement transaction.  The remote side saves first and
/// acknowledges over the existing pairing PSK; only then is the local config
/// committed.  Its service exits immediately after the ACK so systemd can
/// rebuild its portals with the complementary edge.
fn run_topology_apply(
    config_override: Option<PathBuf>,
    peer_id: &str,
    placement: config::RelativePlacement,
) -> Result<(), Box<dyn std::error::Error>> {
    let placement = horizontal_placement(placement)?;
    let (path, mut bridge_config, peer) = configured_peer(config_override, peer_id)?;
    let control = SocketAddr::new(peer.client_endpoint.ip(), DEFAULT_CONTROL_PORT);
    let stream = TcpStream::connect_timeout(&control, Duration::from_secs(8))?;
    stream.set_read_timeout(Some(Duration::from_secs(8)))?;
    stream.set_write_timeout(Some(Duration::from_secs(8)))?;
    let mut connection = SecureConnection::connect(stream, Role::Host, peer.psk())?;
    let request = format!("CBTO1:{}:{}", peer.id, placement.as_str());
    connection.send_payload(request.as_bytes())?;
    let ack = connection.receive_payload()?;
    if ack.as_slice() != b"CBTO1:ok" {
        return Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            "the client rejected the topology update",
        )
        .into());
    }
    bridge_config.set_peer_placement(peer_id, placement)?;
    config::save(&path, &bridge_config)?;
    println!("topology_applied={}", placement.as_str());
    Ok(())
}

fn spawn_topology_control_listener(
    path: PathBuf,
    peer: config::PeerConfig,
) -> Result<Receiver<()>, Box<dyn std::error::Error>> {
    let listen = SocketAddr::new(peer.client_endpoint.ip(), DEFAULT_CONTROL_PORT);
    let listener = TcpListener::bind(listen)?;
    listener.set_nonblocking(true)?;
    let (changed_tx, changed_rx) = sync_channel(1);
    std::thread::spawn(move || loop {
        match listener.accept() {
            Ok((stream, remote)) => {
                let result = (|| -> Result<(), Box<dyn std::error::Error>> {
                    stream.set_read_timeout(Some(Duration::from_secs(8)))?;
                    stream.set_write_timeout(Some(Duration::from_secs(8)))?;
                    let mut connection =
                        SecureConnection::connect(stream, Role::Client, peer.psk())?;
                    let payload = connection.receive_payload()?;
                    let request = std::str::from_utf8(&payload).map_err(|_| {
                        io::Error::new(io::ErrorKind::InvalidData, "invalid topology request")
                    })?;
                    let mut fields = request.split(':');
                    let (Some(version), Some(id), Some(placement), None) =
                        (fields.next(), fields.next(), fields.next(), fields.next())
                    else {
                        return Err(io::Error::new(
                            io::ErrorKind::InvalidData,
                            "invalid topology request",
                        )
                        .into());
                    };
                    if version != "CBTO1" || !id.eq_ignore_ascii_case(&peer.id) {
                        return Err(io::Error::new(
                            io::ErrorKind::PermissionDenied,
                            "topology peer mismatch",
                        )
                        .into());
                    }
                    let host_placement = match placement {
                        "left" => config::RelativePlacement::Left,
                        "right" => config::RelativePlacement::Right,
                        _ => {
                            return Err(io::Error::new(
                                io::ErrorKind::Unsupported,
                                "unsupported topology",
                            )
                            .into())
                        }
                    };
                    let mut config = config::load_or_default(&path)?;
                    config.set_peer_placement(&peer.id, opposite_placement(host_placement))?;
                    config::save(&path, &config)?;
                    connection.send_payload(b"CBTO1:ok")?;
                    changed_tx.send(()).map_err(|_| {
                        io::Error::new(io::ErrorKind::BrokenPipe, "client is stopping")
                    })?;
                    Ok(())
                })();
                if let Err(error) = result {
                    eprintln!("ignored topology control request from {remote}: {error}");
                }
            }
            Err(error) if error.kind() == io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(20));
            }
            Err(error) => {
                eprintln!("topology control listener stopped: {error}");
                return;
            }
        }
    });
    Ok(changed_rx)
}

/// The controlled side owns the clipboard listener just as it owns the input
/// listener. A failed or closed clipboard connection never affects keyboard
/// and mouse forwarding; it retries independently in its worker thread.
fn spawn_clipboard_client(peer: config::PeerConfig) -> Result<(), Box<dyn std::error::Error>> {
    let listen = SocketAddr::new(peer.client_endpoint.ip(), DEFAULT_CLIPBOARD_PORT);
    let listener = TcpListener::bind(listen)?;
    std::thread::spawn(move || loop {
        match listener.accept() {
            Ok((stream, remote)) => {
                match SecureConnection::connect(stream, Role::Client, peer.psk()) {
                    Ok(connection) => {
                        eprintln!("clipboard peer connected from {remote}");
                        if let Err(error) = clipboard::run(connection) {
                            eprintln!("clipboard session ended: {error}");
                        }
                    }
                    Err(error) => eprintln!("ignored clipboard connection from {remote}: {error}"),
                }
            }
            Err(error) => {
                eprintln!("clipboard listener stopped: {error}");
                return;
            }
        }
    });
    Ok(())
}

fn spawn_clipboard_host(peer: config::PeerConfig) {
    std::thread::spawn(move || loop {
        let address = SocketAddr::new(peer.client_endpoint.ip(), DEFAULT_CLIPBOARD_PORT);
        let result = (|| -> Result<(), Box<dyn std::error::Error>> {
            let stream = TcpStream::connect_timeout(&address, Duration::from_secs(5))?;
            let connection = SecureConnection::connect(stream, Role::Host, peer.psk())?;
            eprintln!("clipboard sync connected to {address}");
            clipboard::run(connection)?;
            Ok(())
        })();
        if let Err(error) = result {
            eprintln!("clipboard sync unavailable: {error}");
        }
        std::thread::sleep(Duration::from_secs(2));
    });
}

fn run_clipboard_sync(
    config_override: Option<PathBuf>,
    peer_id: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let (_, _, peer) = configured_peer(config_override, peer_id)?;
    let address = SocketAddr::new(peer.client_endpoint.ip(), DEFAULT_CLIPBOARD_PORT);
    eprintln!("connecting encrypted clipboard sync to {address}");
    let stream = TcpStream::connect_timeout(&address, Duration::from_secs(8))?;
    let connection = SecureConnection::connect(stream, Role::Host, peer.psk())?;
    clipboard::run(connection)?;
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn run_left_edge_demo(
    peer: SocketAddr,
    psk: [u8; 32],
    edge_y: i32,
    local_width: u32,
    local_height: u32,
    peer_x: i32,
    peer_y: i32,
    peer_width: u32,
    peer_height: u32,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut demo = handoff_demo::LeftEdgeDemo::side_by_side(
        local_width,
        local_height,
        peer_x,
        peer_y,
        peer_width,
        peer_height,
    )?;
    let enter = demo.left_barrier_activated(edge_y)?;
    if !matches!(demo.state(), handoff::HandoffState::EntryPending { .. }) {
        return Err(io::Error::other("left barrier did not enter a pending handoff state").into());
    }
    eprintln!("connecting to client at {peer} for simulated left-edge handoff");
    let stream = TcpStream::connect(peer)?;
    let mut connection = SecureConnection::connect(stream, Role::Host, &psk)?;
    connection.set_read_timeout(Some(Duration::from_millis(PEER_TIMEOUT_MS)))?;
    connection.send(enter)?;

    let result = match connection.receive()? {
        Message::EnterAck => {
            if demo.receive_peer_message(Message::EnterAck)? {
                eprintln!(
                    "left-edge handoff acknowledged; no portal/libei input backend is attached, releasing safely"
                );
                Ok(())
            } else {
                Err(io::Error::other("peer ACK did not activate the handoff"))
            }
        }
        Message::EnterRejected => {
            let _ = demo.receive_peer_message(Message::EnterRejected)?;
            Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                "peer rejected the left-edge handoff",
            ))
        }
        message => Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("expected EnterAck or EnterRejected, received {message:?}"),
        )),
    };

    if let Some(release) = demo.release() {
        let _ = connection.send(release);
    }
    if result.is_ok() {
        let _ = connection.send(Message::Goodbye);
    }
    result.map_err(Into::into)
}

fn run_seamless_client(
    listen: SocketAddr,
    psk: [u8; 32],
    peer_width: u32,
    peer_y: i32,
) -> Result<(), Box<dyn std::error::Error>> {
    if peer_width == 0 {
        return Err(
            io::Error::new(io::ErrorKind::InvalidInput, "peer width must be non-zero").into(),
        );
    }
    eprintln!("starting RemoteDesktop and right InputCapture sessions; portal consent is required before listening");
    let injector = seamless::RemoteDesktopInjector::start()?;
    let return_watcher = seamless::EdgeReturnWatcher::start(protocol::WireEdge::Right, peer_y)?;
    run_seamless_client_with_sessions(listen, psk, injector, return_watcher, None)
}

fn run_seamless_client_with_sessions(
    listen: SocketAddr,
    psk: [u8; 32],
    injector: seamless::RemoteDesktopInjector,
    mut return_watcher: seamless::EdgeReturnWatcher,
    topology_changed: Option<Receiver<()>>,
) -> Result<(), Box<dyn std::error::Error>> {
    let listener = TcpListener::bind(listen)?;
    listener.set_nonblocking(true)?;
    eprintln!(
        "seamless client ready; waiting for host on {}",
        listener.local_addr()?
    );
    let (stream, peer) = loop {
        if let Some(receiver) = &topology_changed {
            match receiver.try_recv() {
                Ok(()) | Err(TryRecvError::Disconnected) => {
                    return Err(io::Error::new(
                        io::ErrorKind::Interrupted,
                        "topology updated; restart client portal session",
                    )
                    .into())
                }
                Err(TryRecvError::Empty) => {}
            }
        }
        match listener.accept() {
            Ok(connection) => break connection,
            Err(error) if error.kind() == io::ErrorKind::WouldBlock => {
                std::thread::sleep(CLIENT_IDLE_POLL_INTERVAL);
            }
            Err(error) => return Err(error.into()),
        }
    };
    eprintln!("host TCP connection from {peer}; authenticating");
    let connection = SecureConnection::connect(stream, Role::Client, &psk)?;
    connection.set_read_timeout(Some(Duration::from_millis(PEER_TIMEOUT_MS)))?;
    let mut client = seamless::SeamlessClient::new(injector, connection);
    let mut last_peer_message = Instant::now();

    let result: Result<(), Box<dyn std::error::Error>> = loop {
        if let Some(receiver) = &topology_changed {
            match receiver.try_recv() {
                Ok(()) | Err(TryRecvError::Disconnected) => {
                    break Err(Box::new(io::Error::new(
                        io::ErrorKind::Interrupted,
                        "topology updated; restart client portal session",
                    )))
                }
                Err(TryRecvError::Empty) => {}
            }
        }
        // Always drain portal signals. Otherwise a right-edge activation from
        // before Enter could be mistaken for a return immediately afterward.
        let return_position = return_watcher.poll_exit()?;
        if client.remote_active() {
            if let Some((edge, y)) = return_position {
                let x = match edge {
                    protocol::WireEdge::Right => -1,
                    protocol::WireEdge::Left => {
                        client
                            .entry()
                            .ok_or_else(|| {
                                io::Error::new(
                                    io::ErrorKind::InvalidData,
                                    "left-edge return has no authenticated entry coordinate",
                                )
                            })?
                            .x
                    }
                };
                client.request_exit(edge, handoff::Point { x, y })?;
                eprintln!("client edge return sent; waiting for the next host entry");
                continue;
            }
        }
        match client.poll_next()? {
            Some(message) => {
                last_peer_message = Instant::now();
                // HandoffRelease is the normal acknowledgement of a client
                // right-edge return. It must leave the portal sessions and
                // encrypted connection alive so the next crossing works.
                let terminal = matches!(message, Message::Goodbye);
                client.handle(message)?;
                if terminal {
                    break Ok(());
                }
            }
            None => {
                if client.remote_active()
                    && last_peer_message.elapsed() > Duration::from_millis(PEER_TIMEOUT_MS)
                {
                    break Err(Box::new(io::Error::new(
                        io::ErrorKind::TimedOut,
                        "seamless host heartbeat timed out",
                    )));
                }
                std::thread::sleep(CLIENT_IDLE_POLL_INTERVAL);
            }
        }
    };

    // Safety invariant: every receive, protocol, and injection failure closes
    // the RemoteDesktop sender, which releases its pressed input ledger.
    let release_result = client.close();
    let watcher_result = return_watcher.close();
    result?;
    release_result?;
    watcher_result?;
    eprintln!("seamless client session complete; all remote input released");
    Ok(())
}

fn configured_peer(
    config_override: Option<PathBuf>,
    peer_id: &str,
) -> Result<(PathBuf, config::BridgeConfig, config::PeerConfig), Box<dyn std::error::Error>> {
    let path = resolve_config_path(config_override)?;
    let bridge_config = config::load_or_default(&path)?;
    let peer = bridge_config.peer(peer_id)?.clone();
    Ok((path, bridge_config, peer))
}

fn portal_persistence(
    enabled: bool,
    token: Option<&str>,
) -> Result<portal_persistence::PortalPersistence, Box<dyn std::error::Error>> {
    if !enabled {
        return Ok(portal_persistence::PortalPersistence::disabled());
    }
    let token = token
        .map(portal_persistence::RestoreToken::new)
        .transpose()?;
    Ok(portal_persistence::PortalPersistence::persistent(token))
}

fn persist_returned_tokens(
    path: &std::path::Path,
    bridge_config: &mut config::BridgeConfig,
    peer_id: &str,
    updates: config::RestoreTokenUpdates,
) -> Result<(), Box<dyn std::error::Error>> {
    bridge_config.apply_restore_token_updates(peer_id, updates)?;
    config::save(path, bridge_config)?;
    Ok(())
}

fn run_seamless_client_config(
    config_override: Option<PathBuf>,
    peer_id: &str,
    peer_width: u32,
    peer_y: i32,
) -> Result<(), Box<dyn std::error::Error>> {
    if peer_width == 0 {
        return Err(
            io::Error::new(io::ErrorKind::InvalidInput, "peer width must be non-zero").into(),
        );
    }
    let (path, mut bridge_config, peer) = configured_peer(config_override, peer_id)?;
    let client_placement = horizontal_placement(peer.placement)?;
    // Pairing stores the complementary direction: client right means host is
    // on its right, so return through the client's right edge (and vice versa).
    let return_edge = match client_placement {
        config::RelativePlacement::Right => protocol::WireEdge::Right,
        config::RelativePlacement::Left => protocol::WireEdge::Left,
        config::RelativePlacement::Above | config::RelativePlacement::Below => unreachable!(),
    };

    eprintln!("starting configured RemoteDesktop and right InputCapture sessions; portal consent may be required");
    let mut injector = seamless::RemoteDesktopInjector::start_with_persistence(
        portal_persistence(peer.persistent_permissions, peer.remote_restore_token())?,
    )?;
    let returned_remote = injector
        .take_restore_token()
        .map(|token| token.into_secret());

    let mut return_watcher = match seamless::EdgeReturnWatcher::start_with_persistence(
        return_edge,
        peer_y,
        portal_persistence(peer.persistent_permissions, peer.capture_restore_token())?,
    ) {
        Ok(watcher) => watcher,
        Err(error) => {
            // The RemoteDesktop start has already consumed its restore token.
            // Persist its replacement/clear before returning this failure.
            if peer.persistent_permissions {
                persist_returned_tokens(
                    &path,
                    &mut bridge_config,
                    &peer.id,
                    config::RestoreTokenUpdates::remote(returned_remote),
                )?;
            }
            return Err(error);
        }
    };
    let returned_capture = return_watcher
        .take_restore_token()
        .map(|token| token.into_secret());
    if peer.persistent_permissions {
        // Both starts succeeded, so replace both single-use tokens together in
        // one 0600 atomic config rewrite before accepting network input.
        persist_returned_tokens(
            &path,
            &mut bridge_config,
            &peer.id,
            config::RestoreTokenUpdates::both(returned_capture, returned_remote),
        )?;
    }
    spawn_clipboard_client(peer.clone())?;
    let topology_changed = spawn_topology_control_listener(path, peer.clone())?;
    run_seamless_client_with_sessions(
        peer.client_endpoint,
        *peer.psk(),
        injector,
        return_watcher,
        Some(topology_changed),
    )
}

fn run_seamless_host(
    peer: SocketAddr,
    psk: [u8; 32],
    local_width: u32,
    local_height: u32,
    peer_width: u32,
    peer_height: u32,
    peer_y: i32,
) -> Result<(), Box<dyn std::error::Error>> {
    let peer_x = -i32::try_from(peer_width)
        .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "peer width exceeds i32"))?;
    let local = handoff::Rect::new(0, 0, local_width, local_height).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("invalid local layout: {error:?}"),
        )
    })?;
    let remote = handoff::Rect::new(peer_x, peer_y, peer_width, peer_height).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("invalid peer layout: {error:?}"),
        )
    })?;
    eprintln!("starting InputCapture left-edge session; portal consent is required");
    let capture = seamless::InputCaptureAdapter::start_left(local.x)?;
    run_seamless_host_with_capture(peer, psk, local, remote, handoff::Edge::Left, capture)
}

fn run_seamless_host_with_capture(
    peer: SocketAddr,
    psk: [u8; 32],
    local: handoff::Rect,
    remote: handoff::Rect,
    edge: handoff::Edge,
    capture: seamless::InputCaptureAdapter,
) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("connecting seamless host to client at {peer}");
    // A client starts two portal sessions before it opens its input listener.
    // On a fresh GUI pairing Plasma may wait for the user to approve those
    // sessions, so the old eight-second retry window made a successful pairing
    // look broken. Keep the initial host session alive long enough for that
    // consent and listener handoff to complete.
    let stream = connect_seamless_peer(peer, Duration::from_secs(60))?;
    let connection = SecureConnection::connect(stream, Role::Host, &psk)?;
    connection.set_read_timeout(Some(Duration::from_millis(PEER_TIMEOUT_MS)))?;
    let controller = handoff::HandoffController::new(local, remote, edge);
    let mut host = seamless::SeamlessHost::new(controller, capture, connection);

    let forward_result: Result<(), Box<dyn std::error::Error>> = (|| loop {
        host.activate_once()?;
        if matches!(host.state(), handoff::HandoffState::RemoteActive { .. }) {
            while matches!(host.state(), handoff::HandoffState::RemoteActive { .. }) {
                host.forward_next(Duration::from_millis(HEARTBEAT_INTERVAL_MS))?;
            }
            eprintln!("peer returned to local host; edge barrier remains armed");
            continue;
        }
        eprintln!("peer rejected entry; edge barrier remains armed for another activation");
    })();

    // Cleanup first releases the exact portal activation, then makes a
    // best-effort encrypted release for the peer's pressed input ledger.
    let release_result = host.close();
    forward_result?;
    release_result?;
    Ok(())
}

/// Pairing saves the client configuration before its GUI starts the regular
/// listener. Allow that handoff to complete instead of failing the host on a
/// harmless, short-lived connection refusal.
fn connect_seamless_peer(peer: SocketAddr, timeout: Duration) -> io::Result<TcpStream> {
    let deadline = Instant::now() + timeout;
    loop {
        match TcpStream::connect(peer) {
            Ok(stream) => return Ok(stream),
            Err(error)
                if matches!(
                    error.kind(),
                    io::ErrorKind::ConnectionRefused
                        | io::ErrorKind::TimedOut
                        | io::ErrorKind::ConnectionAborted
                ) && Instant::now() < deadline =>
            {
                std::thread::sleep(Duration::from_millis(200));
            }
            Err(error) => return Err(error),
        }
    }
}

fn run_seamless_host_config(
    config_override: Option<PathBuf>,
    peer_id: &str,
    local_width: u32,
    local_height: u32,
    peer_width: u32,
    peer_height: u32,
    peer_y: i32,
) -> Result<(), Box<dyn std::error::Error>> {
    let (path, mut bridge_config, peer) = configured_peer(config_override, peer_id)?;
    let placement = horizontal_placement(peer.placement)?;
    let (peer_x, edge, capture_edge, capture_x) = match placement {
        config::RelativePlacement::Left => (
            -i32::try_from(peer_width).map_err(|_| {
                io::Error::new(io::ErrorKind::InvalidInput, "peer width exceeds i32")
            })?,
            handoff::Edge::Left,
            portal_spike::CaptureEdge::Left,
            0,
        ),
        config::RelativePlacement::Right => (
            i32::try_from(local_width).map_err(|_| {
                io::Error::new(io::ErrorKind::InvalidInput, "local width exceeds i32")
            })?,
            handoff::Edge::Right,
            portal_spike::CaptureEdge::Right,
            i32::try_from(local_width)
                .map_err(|_| {
                    io::Error::new(io::ErrorKind::InvalidInput, "local width exceeds i32")
                })?
                .saturating_sub(1),
        ),
        config::RelativePlacement::Above | config::RelativePlacement::Below => unreachable!(),
    };
    let local = handoff::Rect::new(0, 0, local_width, local_height).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("invalid local layout: {error:?}"),
        )
    })?;
    let remote = handoff::Rect::new(peer_x, peer_y, peer_width, peer_height).map_err(|error| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("invalid peer layout: {error:?}"),
        )
    })?;
    eprintln!("starting configured InputCapture edge session; portal consent may be required");
    let mut capture = seamless::InputCaptureAdapter::start_with_persistence(
        capture_edge,
        capture_x,
        portal_persistence(peer.persistent_permissions, peer.capture_restore_token())?,
    )?;
    if peer.persistent_permissions {
        persist_returned_tokens(
            &path,
            &mut bridge_config,
            &peer.id,
            config::RestoreTokenUpdates::capture(
                capture
                    .take_restore_token()
                    .map(|token| token.into_secret()),
            ),
        )?;
    }
    spawn_clipboard_host(peer.clone());
    run_seamless_host_with_capture(
        peer.client_endpoint,
        *peer.psk(),
        local,
        remote,
        edge,
        capture,
    )
}

fn run_host(
    peer: SocketAddr,
    psk: [u8; 32],
    devices: &[PathBuf],
    grab: bool,
    demo_events: Option<u32>,
    stop_after_reports: Option<u64>,
) -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("connecting to client at {peer}");
    let stream = TcpStream::connect(peer)?;
    let mut connection = SecureConnection::connect(stream, Role::Host, &psk)?;

    if let Some(report_count) = demo_events {
        for _ in 0..report_count {
            for event in [
                WireInputEvent {
                    event_type: 2,
                    code: 0,
                    value: 3,
                },
                WireInputEvent {
                    event_type: 2,
                    code: 1,
                    value: 2,
                },
                WireInputEvent {
                    event_type: 0,
                    code: 0,
                    value: 0,
                },
            ] {
                connection.send(Message::Input(event))?;
            }
        }
        connection.send(Message::ReleaseAll)?;
        connection.send(Message::Goodbye)?;
        eprintln!("sent {report_count} synthetic pointer report(s)");
        return Ok(());
    }

    let (tx, rx) = sync_channel::<WireInputEvent>(INPUT_QUEUE_CAPACITY);
    let capture = start_capture(devices, grab, tx)?;
    eprintln!(
        "connected; forwarding input from {} device(s)",
        devices.len()
    );

    let mut pressed = BTreeSet::new();
    let mut forwarded_reports = 0_u64;
    let forwarding_result: Result<(), Box<dyn std::error::Error>> = loop {
        match rx.recv_timeout(Duration::from_millis(HEARTBEAT_INTERVAL_MS)) {
            Ok(event) => {
                update_pressed_keys(&mut pressed, event);
                if emergency_chord_active(&pressed, event) {
                    eprintln!("emergency release chord detected; returning input locally");
                    break Ok(());
                }
                if let Err(error) = connection.send(Message::Input(event)) {
                    break Err(Box::new(error));
                }
                if event.event_type == 0 && event.code == 0 && event.value == 0 {
                    forwarded_reports += 1;
                    if stop_after_reports == Some(forwarded_reports) {
                        eprintln!("forwarded requested {forwarded_reports} report(s)");
                        break Ok(());
                    }
                }
            }
            Err(std::sync::mpsc::RecvTimeoutError::Timeout) => {
                if let Err(error) = connection.send(Message::Heartbeat) {
                    break Err(Box::new(error));
                }
            }
            Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                break Err(Box::new(io::Error::new(
                    io::ErrorKind::BrokenPipe,
                    "all input capture workers stopped",
                )));
            }
        }
    };

    // A best-effort release prevents held controls on an orderly host shutdown.
    let graceful = forwarding_result.is_ok();
    let _ = connection.send(Message::ReleaseAll);
    if graceful {
        let _ = connection.send(Message::Goodbye);
    }
    let capture_result = capture.shutdown();
    forwarding_result?;
    capture_result?;
    Ok(())
}

fn update_pressed_keys(pressed: &mut BTreeSet<u16>, event: WireInputEvent) {
    if event.event_type != 1 {
        return;
    }
    match event.value {
        0 => {
            pressed.remove(&event.code);
        }
        1 => {
            pressed.insert(event.code);
        }
        _ => {}
    }
}

fn emergency_chord_active(pressed: &BTreeSet<u16>, event: WireInputEvent) -> bool {
    const KEY_ESC: u16 = 1;
    const CTRL: [u16; 2] = [29, 97];
    const SHIFT: [u16; 2] = [42, 54];
    const ALT: [u16; 2] = [56, 100];

    event.event_type == 1
        && event.code == KEY_ESC
        && event.value == 1
        && CTRL.iter().any(|code| pressed.contains(code))
        && SHIFT.iter().any(|code| pressed.contains(code))
        && ALT.iter().any(|code| pressed.contains(code))
}

fn run_client(
    listen: SocketAddr,
    psk: [u8; 32],
    dry_run: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    let listener = TcpListener::bind(listen)?;
    eprintln!("waiting for host on {}", listener.local_addr()?);
    let (stream, peer) = listener.accept()?;
    eprintln!("host TCP connection from {peer}; authenticating");
    let mut connection = SecureConnection::connect(stream, Role::Client, &psk)?;
    connection.set_read_timeout(Some(Duration::from_millis(PEER_TIMEOUT_MS)))?;
    let mut sink = create_sink(dry_run)?;
    let mut event_count = 0_u64;
    eprintln!(
        "host authenticated; accepting input{}",
        if dry_run { " (dry run)" } else { "" }
    );

    let result: Result<(), Box<dyn std::error::Error>> = loop {
        match connection.receive() {
            Ok(Message::Input(event)) => {
                if let Err(error) = sink.inject(event) {
                    break Err(Box::new(error));
                }
                event_count += 1;
            }
            Ok(Message::Heartbeat) => {}
            Ok(Message::ReleaseAll | Message::HandoffRelease) => {
                if let Err(error) = sink.release_all() {
                    break Err(Box::new(error));
                }
            }
            Ok(Message::Enter { x, y }) => {
                // This acknowledgement only proves encrypted control-plane
                // wiring. Pointer placement is owned by the future portal/EIS
                // backend, so no local coordinates are applied here yet.
                eprintln!("accepted left-edge handoff request at ({x}, {y})");
                if let Err(error) = connection.send(Message::EnterAck) {
                    break Err(Box::new(error));
                }
            }
            Ok(Message::EnterAck | Message::EnterRejected) => {
                break Err(Box::new(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "client received a handoff response without a local request",
                )));
            }
            Ok(Message::ExitRequest { .. }) => {
                break Err(Box::new(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "manual client received a seamless-only exit request",
                )));
            }
            Ok(Message::PointerMotion { .. }) => {
                break Err(Box::new(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "manual client received a seamless-only paired motion frame",
                )));
            }
            Ok(Message::Goodbye) => break Ok(()),
            Err(TransportError::Io(error))
                if matches!(
                    error.kind(),
                    io::ErrorKind::TimedOut | io::ErrorKind::WouldBlock
                ) =>
            {
                break Err(Box::new(io::Error::new(
                    io::ErrorKind::TimedOut,
                    "host heartbeat timed out",
                )));
            }
            Err(error) => break Err(Box::new(error) as Box<dyn std::error::Error>),
        }
    };

    // Safety invariant: every error path releases the virtual key/button state.
    let release_result = sink.release_all();
    result?;
    release_result?;
    eprintln!("session complete; received {event_count} input event(s)");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(code: u16, value: i32) -> WireInputEvent {
        WireInputEvent {
            event_type: 1,
            code,
            value,
        }
    }

    #[test]
    fn emergency_chord_requires_ctrl_alt_shift_and_escape() {
        let mut pressed = BTreeSet::new();
        for event in [key(29, 1), key(56, 1), key(42, 1)] {
            update_pressed_keys(&mut pressed, event);
            assert!(!emergency_chord_active(&pressed, event));
        }
        let escape = key(1, 1);
        update_pressed_keys(&mut pressed, escape);
        assert!(emergency_chord_active(&pressed, escape));
    }

    #[test]
    fn releasing_modifier_disarms_emergency_chord() {
        let mut pressed = BTreeSet::from([29, 56, 42]);
        update_pressed_keys(&mut pressed, key(56, 0));
        let escape = key(1, 1);
        update_pressed_keys(&mut pressed, escape);
        assert!(!emergency_chord_active(&pressed, escape));
    }

    #[test]
    fn cli_exposes_safe_pairing_and_topology_commands() {
        assert!(matches!(
            Cli::try_parse_from(["cachybridge", "config-path"]),
            Ok(Cli {
                command: Command::ConfigPath { .. }
            })
        ));
        assert!(matches!(
            Cli::try_parse_from(["cachybridge", "pair-token", "--output", "/tmp/token"]),
            Ok(Cli {
                command: Command::PairToken { .. }
            })
        ));
        assert!(matches!(
            Cli::try_parse_from(["cachybridge", "pair-code"]),
            Ok(Cli {
                command: Command::PairCode
            })
        ));
        assert!(matches!(
            Cli::try_parse_from([
                "cachybridge",
                "pair-client",
                "--code",
                "ABCDE-FGHJK-LMNPQ-RSTUV-WXYZ2-3",
            ]),
            Ok(Cli {
                command: Command::PairClient { .. }
            })
        ));
        assert!(matches!(
            Cli::try_parse_from([
                "cachybridge",
                "pair-host",
                "--connect",
                "192.168.2.10:45232",
                "--code",
                "ABCDE-FGHJK-LMNPQ-RSTUV-WXYZ2-3",
                "--local-name",
                "Client iMac",
            ]),
            Ok(Cli {
                command: Command::PairHost { .. }
            })
        ));
        assert!(matches!(
            Cli::try_parse_from([
                "cachybridge",
                "peer-add",
                "--name",
                "Left iMac",
                "--local-name",
                "Right iMac",
                "--host-endpoint",
                "192.168.2.10:45231",
                "--client-endpoint",
                "192.168.2.24:45231",
                "--placement",
                "left",
                "--persistent-permissions",
                "--psk-file",
                "/tmp/token",
            ]),
            Ok(Cli {
                command: Command::PeerAdd { .. }
            })
        ));
        assert!(matches!(
            Cli::try_parse_from([
                "cachybridge",
                "seamless-host-config",
                "--peer",
                "0123456789abcdef0123456789abcdef",
                "--local-width",
                "1920",
                "--local-height",
                "1080",
                "--peer-width",
                "1920",
                "--peer-height",
                "1080",
            ]),
            Ok(Cli {
                command: Command::SeamlessHostConfig { .. }
            })
        ));
        assert!(matches!(
            Cli::try_parse_from([
                "cachybridge",
                "seamless-client-config",
                "--peer",
                "0123456789abcdef0123456789abcdef",
                "--peer-width",
                "1920",
            ]),
            Ok(Cli {
                command: Command::SeamlessClientConfig { .. }
            })
        ));
    }

    #[test]
    fn configured_portal_persistence_keeps_tokens_out_of_cli_state() {
        let persistence = portal_persistence(true, Some("restore-token")).unwrap();
        assert!(persistence.is_enabled());
        assert_eq!(
            persistence.restore_token().unwrap().expose_secret(),
            "restore-token"
        );
        assert!(!format!("{persistence:?}").contains("restore-token"));
        assert!(!portal_persistence(false, Some("ignored-token"))
            .unwrap()
            .is_enabled());
    }
}
